import type { AgentPerformanceSnapshot } from "@/core/dashboard/model/types/agent.types";

const caseTrend = [
  { label: "Sep", resolved: 28, averageResponseMinutes: 58 },
  { label: "Oct", resolved: 31, averageResponseMinutes: 55 },
  { label: "Nov", resolved: 29, averageResponseMinutes: 60 },
  { label: "Dec", resolved: 35, averageResponseMinutes: 52 },
  { label: "Jan", resolved: 38, averageResponseMinutes: 48 },
  { label: "Feb", resolved: 41, averageResponseMinutes: 44 },
  { label: "Mar", resolved: 44, averageResponseMinutes: 40 },
  { label: "Apr", resolved: 47, averageResponseMinutes: 38 },
];

const weeklyCases = [
  { day: "Sen", newCases: 5, resolvedCases: 3 },
  { day: "Sel", newCases: 2, resolvedCases: 4 },
  { day: "Rab", newCases: 4, resolvedCases: 2 },
  { day: "Kam", newCases: 3, resolvedCases: 5 },
  { day: "Jum", newCases: 6, resolvedCases: 4 },
  { day: "Sab", newCases: 2, resolvedCases: 3 },
  { day: "Min", newCases: 1, resolvedCases: 2 },
];

const categoryBreakdown = [
  { label: "Keterlambatan", percent: 40 },
  { label: "Pengembalian Dana", percent: 26 },
  { label: "Pembatalan", percent: 21 },
  { label: "Lainnya", percent: 13 },
];

const teamRanking = [
  {
    rank: 1,
    initials: "DS",
    name: "Dian S.",
    score: 97,
    isCurrentAgent: false,
  },
  {
    rank: 2,
    initials: "FN",
    name: "Fajar N.",
    score: 91,
    isCurrentAgent: false,
  },
  {
    rank: 3,
    initials: "YP",
    name: "Yuni P.",
    score: 87,
    isCurrentAgent: false,
  },
  {
    rank: 4,
    initials: "NR",
    name: "Nadia R.",
    score: 84,
    isCurrentAgent: true,
  },
  {
    rank: 5,
    initials: "BW",
    name: "Bagas W.",
    score: 79,
    isCurrentAgent: false,
  },
];

export const agentPerformanceSnapshots: AgentPerformanceSnapshot[] = [
  {
    agentName: "Nadia Rahma",
    dateRange: {
      from: "2026-05-12",
      to: "2026-05-18",
    },
    period: "7d",
    periodLabel: "7 hari terakhir",
    role: "Agen layanan pelanggan",
    slaHealth: {
      onTimePercent: 94,
      activeRiskCount: 3,
      overdueCount: 1,
      handledWithinWindow: 47,
      totalHandled: 50,
    },
    metrics: {
      averageFirstResponseMinutes: 11,
      resolvedToday: 18,
      activeCases: 14,
      qualityScore: 92,
      escalationRatePercent: 6,
    },
    responseTrend: [
      { day: "Sel", minutes: 13, targetMinutes: 15 },
      { day: "Rab", minutes: 12, targetMinutes: 15 },
      { day: "Kam", minutes: 16, targetMinutes: 15 },
      { day: "Jum", minutes: 10, targetMinutes: 15 },
      { day: "Sab", minutes: 14, targetMinutes: 15 },
      { day: "Min", minutes: 9, targetMinutes: 15 },
      { day: "Sen", minutes: 11, targetMinutes: 15 },
    ],
    riskByPeriod: [
      { label: "06:00-09:00", atRisk: 2, overdue: 0 },
      { label: "09:00-12:00", atRisk: 3, overdue: 1 },
      { label: "12:00-15:00", atRisk: 1, overdue: 0 },
      { label: "15:00-18:00", atRisk: 2, overdue: 0 },
    ],
    qualitySignals: [
      {
        label: "Merespons sebelum arahan operasional",
        value: "18 dari 18 kasus ditinjau",
        percent: 96,
        status: "strong",
      },
      {
        label: "Masalah penumpang disebutkan",
        value: "17 dari 18 balasan awal",
        percent: 89,
        status: "strong",
      },
      {
        label: "Penyelesaian konkret tercatat",
        value: "16 dari 18 penutupan",
        percent: 91,
        status: "watch",
      },
      {
        label: "Rata-rata respons awal",
        value: "11 menit dari target 15 menit",
        percent: 83,
        status: "strong",
      },
    ],
    workload: [
      { label: "Ditugaskan", count: 5, slaBand: "on-track" },
      { label: "Diproses", count: 6, slaBand: "at-risk" },
      { label: "Dijawab", count: 2, slaBand: "on-track" },
      { label: "Dieskalasi", count: 1, slaBand: "overdue" },
    ],
    urgentCasesCount: 4,
    oldestActiveCaseHours: 3,
    recentOutcomes: [
      {
        referenceNumber: "KAI-58291",
        category: "Keterlambatan",
        outcome: "resolved",
        slaResult: "on-track",
        qualityScore: 96,
        resolvedAt: "09:42",
      },
      {
        referenceNumber: "KAI-58272",
        category: "Pengembalian Dana",
        outcome: "resolved",
        slaResult: "on-track",
        qualityScore: 91,
        resolvedAt: "09:18",
      },
      {
        referenceNumber: "KAI-58260",
        category: "Pembatalan",
        outcome: "escalated",
        slaResult: "at-risk",
        qualityScore: 84,
        resolvedAt: "08:55",
      },
      {
        referenceNumber: "KAI-58244",
        category: "Barang Tertinggal",
        outcome: "resolved",
        slaResult: "on-track",
        qualityScore: 94,
        resolvedAt: "08:21",
      },
    ],
    caseTrend,
    weeklyCases,
    categoryBreakdown,
    teamRanking,
  },
  {
    agentName: "Nadia Rahma",
    dateRange: {
      from: "2026-04-19",
      to: "2026-05-18",
    },
    period: "30d",
    periodLabel: "30 hari terakhir",
    role: "Agen layanan pelanggan",
    slaHealth: {
      onTimePercent: 88,
      activeRiskCount: 6,
      overdueCount: 2,
      handledWithinWindow: 37,
      totalHandled: 42,
    },
    metrics: {
      averageFirstResponseMinutes: 14,
      resolvedToday: 15,
      activeCases: 19,
      qualityScore: 89,
      escalationRatePercent: 9,
    },
    responseTrend: [
      { day: "Sel", minutes: 15, targetMinutes: 15 },
      { day: "Rab", minutes: 14, targetMinutes: 15 },
      { day: "Kam", minutes: 18, targetMinutes: 15 },
      { day: "Jum", minutes: 12, targetMinutes: 15 },
      { day: "Sab", minutes: 17, targetMinutes: 15 },
      { day: "Min", minutes: 13, targetMinutes: 15 },
      { day: "Sen", minutes: 14, targetMinutes: 15 },
    ],
    riskByPeriod: [
      { label: "10:00-12:00", atRisk: 4, overdue: 1 },
      { label: "12:00-14:00", atRisk: 6, overdue: 2 },
      { label: "14:00-16:00", atRisk: 3, overdue: 1 },
      { label: "16:00-18:00", atRisk: 2, overdue: 0 },
    ],
    qualitySignals: [
      {
        label: "Merespons sebelum arahan operasional",
        value: "14 dari 15 kasus ditinjau",
        percent: 93,
        status: "watch",
      },
      {
        label: "Masalah penumpang disebutkan",
        value: "15 dari 15 balasan awal",
        percent: 91,
        status: "strong",
      },
      {
        label: "Penyelesaian konkret tercatat",
        value: "13 dari 15 penutupan",
        percent: 86,
        status: "watch",
      },
      {
        label: "Rata-rata respons awal",
        value: "14 menit dari target 15 menit",
        percent: 72,
        status: "watch",
      },
    ],
    workload: [
      { label: "Ditugaskan", count: 7, slaBand: "at-risk" },
      { label: "Diproses", count: 8, slaBand: "at-risk" },
      { label: "Dijawab", count: 2, slaBand: "on-track" },
      { label: "Dieskalasi", count: 2, slaBand: "overdue" },
    ],
    urgentCasesCount: 7,
    oldestActiveCaseHours: 5,
    recentOutcomes: [
      {
        referenceNumber: "KAI-58319",
        category: "Pengembalian Dana",
        outcome: "resolved",
        slaResult: "at-risk",
        qualityScore: 88,
        resolvedAt: "13:52",
      },
      {
        referenceNumber: "KAI-58301",
        category: "Keterlambatan",
        outcome: "resolved",
        slaResult: "on-track",
        qualityScore: 93,
        resolvedAt: "13:17",
      },
      {
        referenceNumber: "KAI-58296",
        category: "Petugas",
        outcome: "escalated",
        slaResult: "overdue",
        qualityScore: 81,
        resolvedAt: "12:38",
      },
      {
        referenceNumber: "KAI-58288",
        category: "Pembatalan",
        outcome: "resolved",
        slaResult: "on-track",
        qualityScore: 90,
        resolvedAt: "12:05",
      },
    ],
    caseTrend,
    weeklyCases,
    categoryBreakdown,
    teamRanking,
  },
  {
    agentName: "Nadia Rahma",
    dateRange: {
      from: "2026-02-18",
      to: "2026-05-18",
    },
    period: "90d",
    periodLabel: "90 hari terakhir",
    role: "Agen layanan pelanggan",
    slaHealth: {
      onTimePercent: 91,
      activeRiskCount: 4,
      overdueCount: 1,
      handledWithinWindow: 40,
      totalHandled: 44,
    },
    metrics: {
      averageFirstResponseMinutes: 12,
      resolvedToday: 16,
      activeCases: 12,
      qualityScore: 94,
      escalationRatePercent: 5,
    },
    responseTrend: [
      { day: "Sel", minutes: 12, targetMinutes: 15 },
      { day: "Rab", minutes: 11, targetMinutes: 15 },
      { day: "Kam", minutes: 15, targetMinutes: 15 },
      { day: "Jum", minutes: 13, targetMinutes: 15 },
      { day: "Sab", minutes: 12, targetMinutes: 15 },
      { day: "Min", minutes: 10, targetMinutes: 15 },
      { day: "Sen", minutes: 12, targetMinutes: 15 },
    ],
    riskByPeriod: [
      { label: "16:00-18:00", atRisk: 2, overdue: 0 },
      { label: "18:00-20:00", atRisk: 4, overdue: 1 },
      { label: "20:00-22:00", atRisk: 2, overdue: 0 },
      { label: "22:00-00:00", atRisk: 1, overdue: 0 },
    ],
    qualitySignals: [
      {
        label: "Merespons sebelum arahan operasional",
        value: "16 dari 16 kasus ditinjau",
        percent: 98,
        status: "strong",
      },
      {
        label: "Masalah penumpang disebutkan",
        value: "16 dari 16 balasan awal",
        percent: 95,
        status: "strong",
      },
      {
        label: "Penyelesaian konkret tercatat",
        value: "16 dari 16 penutupan",
        percent: 94,
        status: "strong",
      },
      {
        label: "Rata-rata respons awal",
        value: "12 menit dari target 15 menit",
        percent: 88,
        status: "strong",
      },
    ],
    workload: [
      { label: "Ditugaskan", count: 4, slaBand: "on-track" },
      { label: "Diproses", count: 5, slaBand: "at-risk" },
      { label: "Dijawab", count: 2, slaBand: "on-track" },
      { label: "Dieskalasi", count: 1, slaBand: "overdue" },
    ],
    urgentCasesCount: 3,
    oldestActiveCaseHours: 4,
    recentOutcomes: [
      {
        referenceNumber: "KAI-58362",
        category: "Keterlambatan",
        outcome: "resolved",
        slaResult: "on-track",
        qualityScore: 97,
        resolvedAt: "19:44",
      },
      {
        referenceNumber: "KAI-58349",
        category: "Barang Tertinggal",
        outcome: "resolved",
        slaResult: "on-track",
        qualityScore: 95,
        resolvedAt: "19:03",
      },
      {
        referenceNumber: "KAI-58331",
        category: "Pengembalian Dana",
        outcome: "resolved",
        slaResult: "on-track",
        qualityScore: 92,
        resolvedAt: "18:28",
      },
      {
        referenceNumber: "KAI-58326",
        category: "Pembatalan",
        outcome: "escalated",
        slaResult: "at-risk",
        qualityScore: 86,
        resolvedAt: "18:11",
      },
    ],
    caseTrend,
    weeklyCases,
    categoryBreakdown,
    teamRanking,
  },
];
