import type { ManagerDashboardData } from "../model/manager-dashboard.types";

export const managerDashboardMockData: ManagerDashboardData = {
  metrics: [
    {
      delta: "+34 dari periode lalu",
      icon: "inbox",
      id: "total-complaints",
      label: "Total keluhan",
      tone: "primary",
      trend: "neutral",
      value: "284",
    },
    {
      delta: "81% rasio selesai",
      icon: "shield",
      id: "resolved-complaints",
      label: "Selesai",
      tone: "success",
      trend: "positive",
      value: "231",
    },
    {
      delta: "-8 menit dari periode lalu",
      icon: "timer",
      id: "avg-first-response",
      label: "Rata-rata respons awal",
      tone: "warning",
      trend: "positive",
      value: "44m",
    },
    {
      delta: "+4 dari periode lalu",
      icon: "sparkles",
      id: "escalations",
      label: "Eskalasi",
      tone: "danger",
      trend: "negative",
      value: "18",
    },
    {
      delta: "-0,4 jam dari periode lalu",
      icon: "clock",
      id: "avg-resolution-time",
      label: "Rata-rata waktu selesai",
      tone: "purple",
      trend: "positive",
      value: "2.6h",
    },
  ],
  complaintTrend: [
    { escalated: 4, incoming: 28, label: "Sep", resolved: 22 },
    { escalated: 3, incoming: 30, label: "Oct", resolved: 25 },
    { escalated: 5, incoming: 34, label: "Nov", resolved: 28 },
    { escalated: 3, incoming: 29, label: "Dec", resolved: 24 },
    { escalated: 6, incoming: 36, label: "Jan", resolved: 30 },
    { escalated: 4, incoming: 32, label: "Feb", resolved: 27 },
    { escalated: 7, incoming: 38, label: "Mar", resolved: 32 },
    { escalated: 6, incoming: 37, label: "Apr", resolved: 31 },
  ],
  complaintCategories: [
    {
      id: "ticket_booking",
      label: "Tiket / Booking",
      percentage: 40,
      tone: "primary",
    },
    {
      id: "refund_cancel",
      label: "Refund / Pembatalan",
      percentage: 26,
      tone: "warning",
    },
    {
      id: "app_error",
      label: "Aplikasi Error / Lemot",
      percentage: 21,
      tone: "success",
    },
    {
      id: "lost_item",
      label: "Barang Tertinggal",
      percentage: 8,
      tone: "purple",
    },
    { id: "other", label: "Lainnya", percentage: 5, tone: "muted" },
  ],
  agentPerformance: [
    {
      averageResponseTime: "29m",
      escalationCount: 2,
      id: "dian-s",
      initials: "DS",
      name: "Dian S.",
      qualityScore: 97,
      resolvedCount: 62,
      status: "on-target",
    },
    {
      averageResponseTime: "34m",
      escalationCount: 3,
      id: "fajar-n",
      initials: "FN",
      name: "Fajar N.",
      qualityScore: 91,
      resolvedCount: 55,
      status: "on-target",
    },
    {
      averageResponseTime: "38m",
      escalationCount: 4,
      id: "rizky-a",
      initials: "RA",
      name: "Rizky A.",
      qualityScore: 84,
      resolvedCount: 47,
      status: "on-target",
    },
    {
      averageResponseTime: "57m",
      escalationCount: 6,
      id: "bagas-w",
      initials: "BW",
      name: "Bagas W.",
      qualityScore: 72,
      resolvedCount: 38,
      status: "needs-review",
    },
    {
      averageResponseTime: "62m",
      escalationCount: 3,
      id: "yuni-p",
      initials: "YP",
      name: "Yuni P.",
      qualityScore: 65,
      resolvedCount: 29,
      status: "needs-review",
    },
  ],
  openEscalations: [
    {
      assignedAgent: "Rizky A.",
      category: "Keterlambatan",
      customerName: "Siti Nuraini",
      id: "esc-001",
      relativeTime: "2 jam lalu",
      urgency: "high",
    },
    {
      assignedAgent: "Bagas W.",
      category: "Pengembalian Dana",
      customerName: "Budi Santoso",
      id: "esc-002",
      relativeTime: "4 jam lalu",
      urgency: "high",
    },
    {
      assignedAgent: "Fajar N.",
      category: "Barang Tertinggal",
      customerName: "Ahmad Fauzi",
      id: "esc-003",
      relativeTime: "5 jam lalu",
      urgency: "medium",
    },
    {
      assignedAgent: "Dian S.",
      category: "Pembatalan",
      customerName: "Dewi Rahayu",
      id: "esc-004",
      relativeTime: "7 jam lalu",
      urgency: "medium",
    },
    {
      assignedAgent: "Yuni P.",
      category: "Fasilitas",
      customerName: "Hendra Putra",
      id: "esc-005",
      relativeTime: "9 jam lalu",
      urgency: "low",
    },
  ],
};
